version: '3.7'

services:

  sipproxy:
    image: fonoster/routr:${COMPOSE_PROJECT_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      EXTERN_ADDR: ${DOCKER_HOST_ADDRESS}
      DATA_SOURCE_PROVIDER: redis_data_provider
      INITIAL_API_SECRET: ${SIPPROXY_API_SECRET}
      DATA_SOURCE_PARAMETERS: host=${DS_HOST},port=${DS_PORT},secret=${DS_SECRET}
      BIND_ADDR: 0.0.0.0
      RECORD_ROUTE: "true"
      REGISTRAR_INTF: Internal
      EX_RTP_ENGINE_ENABLED: "true"
      EX_RTP_ENGINE_PROTO: http
      EX_RTP_ENGINE_HOST: ${RTPE_HOST}
      EX_RTP_ENGINE_PORT: ${RTPE_PORT}
      # Setting this to true is breaking the routing workflow in Routr
      EX_CONVERT_TEL_TO_E164: "false"
    ports:
      - ${SIPPROXY_SIP_PORTS}:${SIPPROXY_SIP_PORTS}
      - ${SIPPROXY_SIP_PORT_UDP}:${SIPPROXY_SIP_PORT_UDP}/udp
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost ${SIPPROXY_API_PORT} || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.sipproxy
    networks:
      fonoster:
        aliases:
          - ${SIPPROXY_HOST}
    volumes:
      - ${CONFIG}/log4j2.yml:/opt/routr/config/log4j2.yml:ro

  # Before you start this in production you should limit the traffic to port 8080 
  # to only internal to avoid denial of service on RTPEngine.
  rtpengine:
    image: fonoster/rtpengine:${COMPOSE_PROJECT_VERSION}
    restart: ${RESTART_POLICY}  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rtpengine.entrypoints=internal,websecure"
      - "traefik.http.routers.rtpengine.rule=PathPrefix(`/ng`)"
      - "traefik.http.services.rtpengine.loadbalancer.server.port=8080"
    # Network hostmode seems to only work in Linux systems
    network_mode: "host"
    environment:
      # This will fail if network_mode != host
      PUBLIC_IP: ${DOCKER_HOST_ADDRESS}
      PORT_MIN: ${RTPE_RTP_PORT_START}
      PORT_MAX: ${RTPE_RTP_PORT_END}
      LOG_LEVEL: '6'

  mediaserver:
    image: fonoster/mediaserver:${COMPOSE_PROJECT_VERSION}
    restart: ${RESTART_POLICY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mediaserver.entrypoints=internal,websecure"
      - "traefik.http.routers.mediaserver.rule=PathPrefix(`/ari/playbacks`) || PathPrefix(`/ari/channels`) || PathPrefix(`/ari/events`)"
      - "traefik.http.services.mediaserver.loadbalancer.server.port=8088"
      - "traefik.http.routers.mediaserver.middlewares=basic-auth@docker,session-auth@docker"
      - "traefik.http.middlewares.session-auth.forwardauth.address=http://auth:3000/session_auth"
      - "traefik.http.middlewares.basic-auth.headers.customrequestheaders.Authorization=Basic ${MS_ARI_AUTHORIZATION}"
    environment:
      APISERVER_ENDPOINT: ${AS_HOST}:${HTTP_PORT}
      ALLOW_INSECURE: ${AS_ALLOW_INSECURE}
      ARI_EXTERNAL_URL: ${PUBLIC_URL}
      ARI_INTERNAL_URL: ${MS_ARI_INTERNAL_URL}
      ARI_USERNAME: ${MS_ARI_USERNAME}
      ARI_SECRET: ${MS_ARI_SECRET}
      EXTERN_ADDR: ${DOCKER_HOST_ADDRESS}
      EXTERN_PORT: ${MS_SIP_PORT}
      SIPPROXY_HOST: ${DOCKER_HOST_ADDRESS}
      SIPPROXY_PORT: ${SIPPROXY_SIP_PORT}
      SIPPROXY_USERNAME: ${SIPPROXY_USERNAME}
      SIPPROXY_API_HOST: ${SIPPROXY_API_HOST}
      SIPPROXY_API_USERNAME: ${SIPPROXY_API_USERNAME}
      SIPPROXY_API_SECRET: ${SIPPROXY_API_SECRET}
      SIPPROXY_SECRET: ${SIPPROXY_SECRET}
      RTP_PORT_START: ${MS_RTP_PORT_START}
      RTP_PORT_END: ${MS_RTP_PORT_END}
      # Give asterisk a fake localnet to force it to always advertise its public address
      # Deprecated
      # LOCALNET: '8.8.8.8'
    volumes:
      - data1-1:/home/fonoster
      # TODO: Update image to add user fonoster
      - ${CONFIG}/config:/root/.fonoster/config:ro
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.mediaserver
    networks:
      fonoster:
