const UNAUTHENTICATED = 16;
const UNKNOWN = 2;
const FAILED_PRECONDITION = 9;
const INVALID_ARGUMENT = 3;
const INTERNAL = 13;
const ENTITY_ALREADY_EXIST = 6;
const UNIMPLEMENTED = 12;
const NOT_FOUND = 5;

export {
  UNAUTHENTICATED,
  UNKNOWN,
  FAILED_PRECONDITION,
  INVALID_ARGUMENT,
  INTERNAL,
  ENTITY_ALREADY_EXIST,
  UNIMPLEMENTED,
  NOT_FOUND
};
