const UNAUTHENTICATED = 16
const UNKNOWN = 2
const FAILED_PRECONDITION = 9
const INVALID_ARGUMENT = 3
const INTERNAL = 13

export {
    UNAUTHENTICATED,
    UNKNOWN,
    FAILED_PRECONDITION,
    INVALID_ARGUMENT,
    INTERNAL
}