// source: numbers.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var common_pb = require('./common_pb.js');
goog.object.extend(proto, common_pb);
var appmanager_pb = require('./appmanager_pb.js');
goog.object.extend(proto, appmanager_pb);
goog.exportSymbol('proto.fonos.numbers.v1alpha1.CreateNumberRequest', null, global);
goog.exportSymbol('proto.fonos.numbers.v1alpha1.DeleteNumberRequest', null, global);
goog.exportSymbol('proto.fonos.numbers.v1alpha1.GetIngressAppRequest', null, global);
goog.exportSymbol('proto.fonos.numbers.v1alpha1.GetNumberRequest', null, global);
goog.exportSymbol('proto.fonos.numbers.v1alpha1.ListNumbersRequest', null, global);
goog.exportSymbol('proto.fonos.numbers.v1alpha1.ListNumbersResponse', null, global);
goog.exportSymbol('proto.fonos.numbers.v1alpha1.Number', null, global);
goog.exportSymbol('proto.fonos.numbers.v1alpha1.UpdateNumberRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fonos.numbers.v1alpha1.ListNumbersRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fonos.numbers.v1alpha1.ListNumbersRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fonos.numbers.v1alpha1.ListNumbersRequest.displayName = 'proto.fonos.numbers.v1alpha1.ListNumbersRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fonos.numbers.v1alpha1.ListNumbersResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.fonos.numbers.v1alpha1.ListNumbersResponse.repeatedFields_, null);
};
goog.inherits(proto.fonos.numbers.v1alpha1.ListNumbersResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fonos.numbers.v1alpha1.ListNumbersResponse.displayName = 'proto.fonos.numbers.v1alpha1.ListNumbersResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fonos.numbers.v1alpha1.CreateNumberRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fonos.numbers.v1alpha1.CreateNumberRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fonos.numbers.v1alpha1.CreateNumberRequest.displayName = 'proto.fonos.numbers.v1alpha1.CreateNumberRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fonos.numbers.v1alpha1.UpdateNumberRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fonos.numbers.v1alpha1.UpdateNumberRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fonos.numbers.v1alpha1.UpdateNumberRequest.displayName = 'proto.fonos.numbers.v1alpha1.UpdateNumberRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fonos.numbers.v1alpha1.GetNumberRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fonos.numbers.v1alpha1.GetNumberRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fonos.numbers.v1alpha1.GetNumberRequest.displayName = 'proto.fonos.numbers.v1alpha1.GetNumberRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fonos.numbers.v1alpha1.GetIngressAppRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fonos.numbers.v1alpha1.GetIngressAppRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fonos.numbers.v1alpha1.GetIngressAppRequest.displayName = 'proto.fonos.numbers.v1alpha1.GetIngressAppRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fonos.numbers.v1alpha1.DeleteNumberRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fonos.numbers.v1alpha1.DeleteNumberRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fonos.numbers.v1alpha1.DeleteNumberRequest.displayName = 'proto.fonos.numbers.v1alpha1.DeleteNumberRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fonos.numbers.v1alpha1.Number = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fonos.numbers.v1alpha1.Number, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fonos.numbers.v1alpha1.Number.displayName = 'proto.fonos.numbers.v1alpha1.Number';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fonos.numbers.v1alpha1.ListNumbersRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.fonos.numbers.v1alpha1.ListNumbersRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fonos.numbers.v1alpha1.ListNumbersRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fonos.numbers.v1alpha1.ListNumbersRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    pageSize: jspb.Message.getFieldWithDefault(msg, 1, 0),
    pageToken: jspb.Message.getFieldWithDefault(msg, 2, ""),
    view: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fonos.numbers.v1alpha1.ListNumbersRequest}
 */
proto.fonos.numbers.v1alpha1.ListNumbersRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fonos.numbers.v1alpha1.ListNumbersRequest;
  return proto.fonos.numbers.v1alpha1.ListNumbersRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fonos.numbers.v1alpha1.ListNumbersRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fonos.numbers.v1alpha1.ListNumbersRequest}
 */
proto.fonos.numbers.v1alpha1.ListNumbersRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageSize(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageToken(value);
      break;
    case 3:
      var value = /** @type {!proto.fonos.common.v1alpha1.View} */ (reader.readEnum());
      msg.setView(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fonos.numbers.v1alpha1.ListNumbersRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fonos.numbers.v1alpha1.ListNumbersRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fonos.numbers.v1alpha1.ListNumbersRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fonos.numbers.v1alpha1.ListNumbersRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPageSize();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getPageToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getView();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional int32 page_size = 1;
 * @return {number}
 */
proto.fonos.numbers.v1alpha1.ListNumbersRequest.prototype.getPageSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.fonos.numbers.v1alpha1.ListNumbersRequest} returns this
 */
proto.fonos.numbers.v1alpha1.ListNumbersRequest.prototype.setPageSize = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string page_token = 2;
 * @return {string}
 */
proto.fonos.numbers.v1alpha1.ListNumbersRequest.prototype.getPageToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.fonos.numbers.v1alpha1.ListNumbersRequest} returns this
 */
proto.fonos.numbers.v1alpha1.ListNumbersRequest.prototype.setPageToken = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional fonos.common.v1alpha1.View view = 3;
 * @return {!proto.fonos.common.v1alpha1.View}
 */
proto.fonos.numbers.v1alpha1.ListNumbersRequest.prototype.getView = function() {
  return /** @type {!proto.fonos.common.v1alpha1.View} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.fonos.common.v1alpha1.View} value
 * @return {!proto.fonos.numbers.v1alpha1.ListNumbersRequest} returns this
 */
proto.fonos.numbers.v1alpha1.ListNumbersRequest.prototype.setView = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.fonos.numbers.v1alpha1.ListNumbersResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fonos.numbers.v1alpha1.ListNumbersResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.fonos.numbers.v1alpha1.ListNumbersResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fonos.numbers.v1alpha1.ListNumbersResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fonos.numbers.v1alpha1.ListNumbersResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    numbersList: jspb.Message.toObjectList(msg.getNumbersList(),
    proto.fonos.numbers.v1alpha1.Number.toObject, includeInstance),
    nextPageToken: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fonos.numbers.v1alpha1.ListNumbersResponse}
 */
proto.fonos.numbers.v1alpha1.ListNumbersResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fonos.numbers.v1alpha1.ListNumbersResponse;
  return proto.fonos.numbers.v1alpha1.ListNumbersResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fonos.numbers.v1alpha1.ListNumbersResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fonos.numbers.v1alpha1.ListNumbersResponse}
 */
proto.fonos.numbers.v1alpha1.ListNumbersResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.fonos.numbers.v1alpha1.Number;
      reader.readMessage(value,proto.fonos.numbers.v1alpha1.Number.deserializeBinaryFromReader);
      msg.addNumbers(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNextPageToken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fonos.numbers.v1alpha1.ListNumbersResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fonos.numbers.v1alpha1.ListNumbersResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fonos.numbers.v1alpha1.ListNumbersResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fonos.numbers.v1alpha1.ListNumbersResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNumbersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.fonos.numbers.v1alpha1.Number.serializeBinaryToWriter
    );
  }
  f = message.getNextPageToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * repeated Number numbers = 1;
 * @return {!Array<!proto.fonos.numbers.v1alpha1.Number>}
 */
proto.fonos.numbers.v1alpha1.ListNumbersResponse.prototype.getNumbersList = function() {
  return /** @type{!Array<!proto.fonos.numbers.v1alpha1.Number>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.fonos.numbers.v1alpha1.Number, 1));
};


/**
 * @param {!Array<!proto.fonos.numbers.v1alpha1.Number>} value
 * @return {!proto.fonos.numbers.v1alpha1.ListNumbersResponse} returns this
*/
proto.fonos.numbers.v1alpha1.ListNumbersResponse.prototype.setNumbersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.fonos.numbers.v1alpha1.Number=} opt_value
 * @param {number=} opt_index
 * @return {!proto.fonos.numbers.v1alpha1.Number}
 */
proto.fonos.numbers.v1alpha1.ListNumbersResponse.prototype.addNumbers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.fonos.numbers.v1alpha1.Number, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.fonos.numbers.v1alpha1.ListNumbersResponse} returns this
 */
proto.fonos.numbers.v1alpha1.ListNumbersResponse.prototype.clearNumbersList = function() {
  return this.setNumbersList([]);
};


/**
 * optional string next_page_token = 2;
 * @return {string}
 */
proto.fonos.numbers.v1alpha1.ListNumbersResponse.prototype.getNextPageToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.fonos.numbers.v1alpha1.ListNumbersResponse} returns this
 */
proto.fonos.numbers.v1alpha1.ListNumbersResponse.prototype.setNextPageToken = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fonos.numbers.v1alpha1.CreateNumberRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.fonos.numbers.v1alpha1.CreateNumberRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fonos.numbers.v1alpha1.CreateNumberRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fonos.numbers.v1alpha1.CreateNumberRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    number: (f = msg.getNumber()) && proto.fonos.numbers.v1alpha1.Number.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fonos.numbers.v1alpha1.CreateNumberRequest}
 */
proto.fonos.numbers.v1alpha1.CreateNumberRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fonos.numbers.v1alpha1.CreateNumberRequest;
  return proto.fonos.numbers.v1alpha1.CreateNumberRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fonos.numbers.v1alpha1.CreateNumberRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fonos.numbers.v1alpha1.CreateNumberRequest}
 */
proto.fonos.numbers.v1alpha1.CreateNumberRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.fonos.numbers.v1alpha1.Number;
      reader.readMessage(value,proto.fonos.numbers.v1alpha1.Number.deserializeBinaryFromReader);
      msg.setNumber(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fonos.numbers.v1alpha1.CreateNumberRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fonos.numbers.v1alpha1.CreateNumberRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fonos.numbers.v1alpha1.CreateNumberRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fonos.numbers.v1alpha1.CreateNumberRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNumber();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.fonos.numbers.v1alpha1.Number.serializeBinaryToWriter
    );
  }
};


/**
 * optional Number number = 1;
 * @return {?proto.fonos.numbers.v1alpha1.Number}
 */
proto.fonos.numbers.v1alpha1.CreateNumberRequest.prototype.getNumber = function() {
  return /** @type{?proto.fonos.numbers.v1alpha1.Number} */ (
    jspb.Message.getWrapperField(this, proto.fonos.numbers.v1alpha1.Number, 1));
};


/**
 * @param {?proto.fonos.numbers.v1alpha1.Number|undefined} value
 * @return {!proto.fonos.numbers.v1alpha1.CreateNumberRequest} returns this
*/
proto.fonos.numbers.v1alpha1.CreateNumberRequest.prototype.setNumber = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.fonos.numbers.v1alpha1.CreateNumberRequest} returns this
 */
proto.fonos.numbers.v1alpha1.CreateNumberRequest.prototype.clearNumber = function() {
  return this.setNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.fonos.numbers.v1alpha1.CreateNumberRequest.prototype.hasNumber = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fonos.numbers.v1alpha1.UpdateNumberRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.fonos.numbers.v1alpha1.UpdateNumberRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fonos.numbers.v1alpha1.UpdateNumberRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fonos.numbers.v1alpha1.UpdateNumberRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    number: (f = msg.getNumber()) && proto.fonos.numbers.v1alpha1.Number.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fonos.numbers.v1alpha1.UpdateNumberRequest}
 */
proto.fonos.numbers.v1alpha1.UpdateNumberRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fonos.numbers.v1alpha1.UpdateNumberRequest;
  return proto.fonos.numbers.v1alpha1.UpdateNumberRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fonos.numbers.v1alpha1.UpdateNumberRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fonos.numbers.v1alpha1.UpdateNumberRequest}
 */
proto.fonos.numbers.v1alpha1.UpdateNumberRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.fonos.numbers.v1alpha1.Number;
      reader.readMessage(value,proto.fonos.numbers.v1alpha1.Number.deserializeBinaryFromReader);
      msg.setNumber(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fonos.numbers.v1alpha1.UpdateNumberRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fonos.numbers.v1alpha1.UpdateNumberRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fonos.numbers.v1alpha1.UpdateNumberRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fonos.numbers.v1alpha1.UpdateNumberRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNumber();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.fonos.numbers.v1alpha1.Number.serializeBinaryToWriter
    );
  }
};


/**
 * optional Number number = 1;
 * @return {?proto.fonos.numbers.v1alpha1.Number}
 */
proto.fonos.numbers.v1alpha1.UpdateNumberRequest.prototype.getNumber = function() {
  return /** @type{?proto.fonos.numbers.v1alpha1.Number} */ (
    jspb.Message.getWrapperField(this, proto.fonos.numbers.v1alpha1.Number, 1));
};


/**
 * @param {?proto.fonos.numbers.v1alpha1.Number|undefined} value
 * @return {!proto.fonos.numbers.v1alpha1.UpdateNumberRequest} returns this
*/
proto.fonos.numbers.v1alpha1.UpdateNumberRequest.prototype.setNumber = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.fonos.numbers.v1alpha1.UpdateNumberRequest} returns this
 */
proto.fonos.numbers.v1alpha1.UpdateNumberRequest.prototype.clearNumber = function() {
  return this.setNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.fonos.numbers.v1alpha1.UpdateNumberRequest.prototype.hasNumber = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fonos.numbers.v1alpha1.GetNumberRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.fonos.numbers.v1alpha1.GetNumberRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fonos.numbers.v1alpha1.GetNumberRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fonos.numbers.v1alpha1.GetNumberRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ref: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fonos.numbers.v1alpha1.GetNumberRequest}
 */
proto.fonos.numbers.v1alpha1.GetNumberRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fonos.numbers.v1alpha1.GetNumberRequest;
  return proto.fonos.numbers.v1alpha1.GetNumberRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fonos.numbers.v1alpha1.GetNumberRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fonos.numbers.v1alpha1.GetNumberRequest}
 */
proto.fonos.numbers.v1alpha1.GetNumberRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRef(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fonos.numbers.v1alpha1.GetNumberRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fonos.numbers.v1alpha1.GetNumberRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fonos.numbers.v1alpha1.GetNumberRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fonos.numbers.v1alpha1.GetNumberRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRef();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string ref = 1;
 * @return {string}
 */
proto.fonos.numbers.v1alpha1.GetNumberRequest.prototype.getRef = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.fonos.numbers.v1alpha1.GetNumberRequest} returns this
 */
proto.fonos.numbers.v1alpha1.GetNumberRequest.prototype.setRef = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fonos.numbers.v1alpha1.GetIngressAppRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.fonos.numbers.v1alpha1.GetIngressAppRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fonos.numbers.v1alpha1.GetIngressAppRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fonos.numbers.v1alpha1.GetIngressAppRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    e164Number: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fonos.numbers.v1alpha1.GetIngressAppRequest}
 */
proto.fonos.numbers.v1alpha1.GetIngressAppRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fonos.numbers.v1alpha1.GetIngressAppRequest;
  return proto.fonos.numbers.v1alpha1.GetIngressAppRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fonos.numbers.v1alpha1.GetIngressAppRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fonos.numbers.v1alpha1.GetIngressAppRequest}
 */
proto.fonos.numbers.v1alpha1.GetIngressAppRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setE164Number(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fonos.numbers.v1alpha1.GetIngressAppRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fonos.numbers.v1alpha1.GetIngressAppRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fonos.numbers.v1alpha1.GetIngressAppRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fonos.numbers.v1alpha1.GetIngressAppRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getE164Number();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string e164_number = 1;
 * @return {string}
 */
proto.fonos.numbers.v1alpha1.GetIngressAppRequest.prototype.getE164Number = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.fonos.numbers.v1alpha1.GetIngressAppRequest} returns this
 */
proto.fonos.numbers.v1alpha1.GetIngressAppRequest.prototype.setE164Number = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fonos.numbers.v1alpha1.DeleteNumberRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.fonos.numbers.v1alpha1.DeleteNumberRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fonos.numbers.v1alpha1.DeleteNumberRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fonos.numbers.v1alpha1.DeleteNumberRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ref: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fonos.numbers.v1alpha1.DeleteNumberRequest}
 */
proto.fonos.numbers.v1alpha1.DeleteNumberRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fonos.numbers.v1alpha1.DeleteNumberRequest;
  return proto.fonos.numbers.v1alpha1.DeleteNumberRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fonos.numbers.v1alpha1.DeleteNumberRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fonos.numbers.v1alpha1.DeleteNumberRequest}
 */
proto.fonos.numbers.v1alpha1.DeleteNumberRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRef(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fonos.numbers.v1alpha1.DeleteNumberRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fonos.numbers.v1alpha1.DeleteNumberRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fonos.numbers.v1alpha1.DeleteNumberRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fonos.numbers.v1alpha1.DeleteNumberRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRef();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string ref = 1;
 * @return {string}
 */
proto.fonos.numbers.v1alpha1.DeleteNumberRequest.prototype.getRef = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.fonos.numbers.v1alpha1.DeleteNumberRequest} returns this
 */
proto.fonos.numbers.v1alpha1.DeleteNumberRequest.prototype.setRef = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fonos.numbers.v1alpha1.Number.prototype.toObject = function(opt_includeInstance) {
  return proto.fonos.numbers.v1alpha1.Number.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fonos.numbers.v1alpha1.Number} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fonos.numbers.v1alpha1.Number.toObject = function(includeInstance, msg) {
  var f, obj = {
    ref: jspb.Message.getFieldWithDefault(msg, 1, ""),
    providerRef: jspb.Message.getFieldWithDefault(msg, 2, ""),
    e164Number: jspb.Message.getFieldWithDefault(msg, 3, ""),
    aorLink: jspb.Message.getFieldWithDefault(msg, 4, ""),
    ingressApp: jspb.Message.getFieldWithDefault(msg, 5, ""),
    createTime: jspb.Message.getFieldWithDefault(msg, 6, ""),
    updateTime: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fonos.numbers.v1alpha1.Number}
 */
proto.fonos.numbers.v1alpha1.Number.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fonos.numbers.v1alpha1.Number;
  return proto.fonos.numbers.v1alpha1.Number.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fonos.numbers.v1alpha1.Number} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fonos.numbers.v1alpha1.Number}
 */
proto.fonos.numbers.v1alpha1.Number.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRef(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setProviderRef(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setE164Number(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAorLink(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setIngressApp(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreateTime(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdateTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fonos.numbers.v1alpha1.Number.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fonos.numbers.v1alpha1.Number.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fonos.numbers.v1alpha1.Number} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fonos.numbers.v1alpha1.Number.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRef();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProviderRef();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getE164Number();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAorLink();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getIngressApp();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCreateTime();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getUpdateTime();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional string ref = 1;
 * @return {string}
 */
proto.fonos.numbers.v1alpha1.Number.prototype.getRef = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.fonos.numbers.v1alpha1.Number} returns this
 */
proto.fonos.numbers.v1alpha1.Number.prototype.setRef = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string provider_ref = 2;
 * @return {string}
 */
proto.fonos.numbers.v1alpha1.Number.prototype.getProviderRef = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.fonos.numbers.v1alpha1.Number} returns this
 */
proto.fonos.numbers.v1alpha1.Number.prototype.setProviderRef = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string e164_number = 3;
 * @return {string}
 */
proto.fonos.numbers.v1alpha1.Number.prototype.getE164Number = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.fonos.numbers.v1alpha1.Number} returns this
 */
proto.fonos.numbers.v1alpha1.Number.prototype.setE164Number = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string aor_link = 4;
 * @return {string}
 */
proto.fonos.numbers.v1alpha1.Number.prototype.getAorLink = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.fonos.numbers.v1alpha1.Number} returns this
 */
proto.fonos.numbers.v1alpha1.Number.prototype.setAorLink = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string ingress_app = 5;
 * @return {string}
 */
proto.fonos.numbers.v1alpha1.Number.prototype.getIngressApp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.fonos.numbers.v1alpha1.Number} returns this
 */
proto.fonos.numbers.v1alpha1.Number.prototype.setIngressApp = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string create_time = 6;
 * @return {string}
 */
proto.fonos.numbers.v1alpha1.Number.prototype.getCreateTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.fonos.numbers.v1alpha1.Number} returns this
 */
proto.fonos.numbers.v1alpha1.Number.prototype.setCreateTime = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string update_time = 7;
 * @return {string}
 */
proto.fonos.numbers.v1alpha1.Number.prototype.getUpdateTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.fonos.numbers.v1alpha1.Number} returns this
 */
proto.fonos.numbers.v1alpha1.Number.prototype.setUpdateTime = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


goog.object.extend(exports, proto.fonos.numbers.v1alpha1);
