FROM node:9-alpine
LABEL maintainer="Pedro Sanders <fonosterteam@fonoster.com>"

WORKDIR /work
COPY etc/gen_jwt_token.js /work/gen_jwt_token.js
RUN npm install jsonwebtoken
CMD ["node", "gen_jwt_token.js"]
