# Required dependencies

version: '3.7'

networks:
  fonos:

volumes:
  data1-1:
    external: true

services:

  fs:
    image: ${FS_IMAGE}
    restart: ${RESTART_POLICY}
    command: minio server /fonos
    volumes:
      - data1-1:/fonos
    environment:
      MINIO_ACCESS_KEY: ${FS_USERNAME}
      MINIO_SECRET_KEY: ${FS_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.fs
    networks:
      fonos:
        aliases:
          - ${FS_HOST}
