name: add contributors

on:
  workflow_dispatch:
  push:
    branches:
     - main

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: akhilmhdh/contributors-readme-action@v2.3.11
        with:
          image_size: 100
          columns_per_row: 6
          readme_path: README.md
          commit_message: "docs(README): update contributors"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
