name: publish apiserver

on:
  push:
    branches:
      - main
    paths:
      - 'mods/apiserver/**'
      - 'mods/authz/**'      # Added as potential dependency
      - 'mods/common/**'
      - 'mods/identity/**'   # Added as potential dependency
      - 'mods/logger/**'     # Added as potential dependency
      - 'mods/sipnet/**'     # Added as potential dependency
      - 'mods/streams/**'    # Added as potential dependency
      - 'mods/types/**'
      - 'lerna.json'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/publish-apiserver.yaml'
  workflow_dispatch: {} # Keep manual dispatch if desired

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Get version
        run: |
          lerna_version=$(node -p "require('./lerna.json').version")
          echo "LERNA_VERSION=$lerna_version" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish the APIServer to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: enesgul23/apiserver
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          context: .
          dockerfile: mods/apiserver/Dockerfile     
          tags: "latest,${{ env.LERNA_VERSION }}"
          platforms: linux/amd64,linux/arm64