name: unit tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'mods/**'
      - 'package.json'
      - 'package-lock.json'
      - '.env.example.dev'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Run unit tests
      run: |
        npm run test 